#Config Server는 pri-board-service라는 애플리케이션이 Config Server에 설정을 요청할 때
#pri-board-service.yml 파일에서 설정을 읽어 제공
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/pri_board_prod
    username: root
    password: mariadb
    driver-class-name: org.mariadb.jdbc.Driver